language: node_js

node_js:
  - 15
  - 16

script:
  - npm config set progress false --silent

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release