language: node_js

branches:
  only:
  - main

node_js:
  - 15

jobs:
  include:
    - stage: release
      node_js: 15
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
