addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libc6-dev


language: node_js

node_js:
  - 15

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release